import {useEffect,useMemo,useRef,useState} from 'react'
import {EditorState} from '@codemirror/state'
import {EditorView,keymap,lineNumbers,highlightActiveLine} from '@codemirror/view'
import {defaultKeymap,history,historyKeymap} from '@codemirror/commands'
import {markdown,markdownLanguage} from '@codemirror/lang-markdown'
import {oneDark} from '@codemirror/theme-one-dark'
import {marked} from 'marked'
import katex from 'katex'
import 'katex/dist/katex.min.css'

type Item={_id:string;title?:string;source?:string;_content?:string;date?:string;categories?:string[];tags?:string[];isDraft?:boolean}
const api=async <T,>(path:string,init?:RequestInit):Promise<T>=>{const r=await fetch('/admin/api/'+path,init);if(!r.ok)throw Error(await r.text()||'请求失败');return r.json()}
function renderMarkdown(source:string){let html=marked.parse(source,{breaks:true,gfm:true}) as string;html=html.replace(/\$\$([\s\S]+?)\$\$/g,(_,x)=>katex.renderToString(x,{displayMode:true,throwOnError:false})).replace(/\$([^$\n]+?)\$/g,(_,x)=>katex.renderToString(x,{throwOnError:false}));return html}
export function EditorApp(){const [mode,setMode]=useState<'posts'|'pages'>('posts'),[items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState<Item|null>(null),[preview,setPreview]=useState(false),[query,setQuery]=useState(''),[tree,setTree]=useState(true),[status,setStatus]=useState('就绪');const editorRef=useRef<HTMLDivElement>(null),viewRef=useRef<EditorView|null>(null);
 const load=async()=>{setStatus('正在加载…');const data=await api<Item[]>(mode+'/list');setItems(data);setStatus('就绪')};useEffect(()=>{load()},[mode]);
 useEffect(()=>{if(!selected||!editorRef.current)return;viewRef.current?.destroy();const s=EditorState.create({doc:selected._content||'',extensions:[lineNumbers(),highlightActiveLine(),history(),keymap.of([...defaultKeymap,...historyKeymap]),markdown({base:markdownLanguage}),oneDark,EditorView.updateListener.of(u=>{if(u.docChanged)setStatus('未保存')})]});viewRef.current=new EditorView({state:s,parent:editorRef.current});return()=>viewRef.current?.destroy()},[selected]);
 const visible=useMemo(()=>items.filter(x=>!query||[x.title,x.source,(x.categories||[]).join(' '),(x.tags||[]).join(' ')].join(' ').toLowerCase().includes(query.toLowerCase())),[items,query]);const save=async()=>{if(!selected||!viewRef.current)return;const body={title:selected.title,date:selected.date||new Date().toISOString(),_content:viewRef.current.state.doc.toString(),categories:selected.categories,tags:selected.tags};await api(mode+'/'+selected._id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setStatus('已保存');load()};return <div className="app-shell"><header><div className="brand"><strong>Purslane Notes</strong><span>本机编辑器</span></div><nav><button className={mode==='posts'?'active':''} onClick={()=>{setMode('posts');setSelected(null)}}>文章</button><button className={mode==='pages'?'active':''} onClick={()=>{setMode('pages');setSelected(null)}}>页面</button></nav><span className="status">{status}</span></header><div className="commandbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索文件、标题、分类或标签"/><button onClick={()=>setTree(!tree)}>{tree?'快速定位':'树形目录'}</button><button onClick={save}>保存</button></div><main className={tree?'workspace':'workspace locator'}><aside className="sidebar"><h3>{mode==='posts'?'文章目录':'页面目录'}</h3>{visible.map(i=><div draggable key={i._id} className={selected?._id===i._id?'file active':'file'} onClick={()=>setSelected(i)} onDragEnd={async()=>{}}>{i.title||i.source}</div>)}</aside><section className="editor-pane"><div className="editor-tabs"><button className={!preview?'active':''} onClick={()=>setPreview(false)}>编辑</button><button className={preview?'active':''} onClick={()=>setPreview(true)}>预览</button></div>{preview?<article className="preview" dangerouslySetInnerHTML={{__html:renderMarkdown(viewRef.current?.state.doc.toString()||selected?._content||'')}}/>:<div ref={editorRef} className="code-editor"/>}</section></main></div>}

