'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),join=v=>Array.isArray(v)?v.join(', '):(v||''),split=v=>(v||'').split(',').map(x=>x.trim()).filter(Boolean),dateValue=v=>{const d=new Date(v);return isNaN(d)?'':d.toISOString().slice(0,16)};
const state={mode:'posts',items:[],selected:null,query:'',filter:'all',tree:true,dirty:false};const cache=new Map();
const api={get:async p=>{if(p.endsWith('/list')&&cache.has(p))return cache.get(p);const r=await fetch('/admin/api/'+p);if(!r.ok)throw Error('请求失败 '+r.status);const d=await r.json();if(p.endsWith('/list'))cache.set(p,d);return d},post:async(p,b)=>{const r=await fetch('/admin/api/'+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b||{})});const t=await r.text();if(!r.ok)throw Error(t||'请求失败');cache.clear();return t?JSON.parse(t):{}}};
function toast(m){let t=$('.ux-toast');if(!t){t=document.createElement('div');t.className='ux-toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1800)}
function folderTree(items){const root={};items.forEach(i=>{let parts=Array.isArray(i.categories)&&i.categories.length?i.categories:['未分类'];let n=root;parts.forEach(p=>{n[p]??={};n=n[p]});(n.files??=[]).push(i)});function branch(n){let keys=Object.keys(n).filter(k=>k!=='files'),out='';for(const k of keys){let x=n[k],label=k;while(!x.files?.length&&Object.keys(x).filter(a=>a!=='files').length===1){const q=Object.keys(x).find(a=>a!=='files');label+=' / '+q;x=x[q]}out+='<div class="tree-folder" data-path="_posts/'+label.replaceAll(' / ','/')+'"><span class="chevron">▾</span>'+esc(label)+'</div><div class="tree-children">'+branch(x)+'</div>'}return out+(n.files||[]).map(i=>'<div class="tree-file" draggable="true" data-id="'+i._id+'"><span class="file-icon"></span>'+esc(i.title||'未命名')+'</div>').join('')}return branch(root)}
function treeHtml(){if(state.mode==='pages')return '<div class="tree-folder" data-path="pages"><span class="chevron">▾</span>pages</div><div class="tree-children">'+state.items.map(i=>'<div class="tree-file" draggable="true" data-id="'+i._id+'"><span class="file-icon"></span>'+esc(i.title||i.source)+'</div>').join('')+'</div>';return '<div class="tree-folder" data-path="_posts"><span class="chevron">▾</span>_posts</div><div class="tree-children">'+folderTree(state.items)+'</div>'}
async function load(){if(state.mode==='help')return renderHelp();const noun=state.mode==='posts'?'文章':'页面';try{state.items=(await api.get(state.mode+'/list')).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0));render()}catch(e){$('#app').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
function render(){const noun=state.mode==='posts'?'文章':'页面';$('#app').innerHTML='<div class="toolbar"><input id="q" placeholder="搜索标题、标签、分类或文件名"><select id="filter"><option value="all">全部</option><option value="draft">草稿</option><option value="published">已发布</option></select><button id="newBtn" class="primary">新建'+noun+'</button><button id="refresh" class="ghost">刷新</button><button id="viewBtn" class="ghost">'+(state.tree?'切换快速定位':'切换树形图')+'</button><span class="command-hint">Ctrl+K 搜索 · Ctrl+Shift+P 预览</span></div><div class="workspace '+(state.tree?'':'locator-open')+'"><aside class="explorer panel" id="explorer"><h3>'+ (state.mode==='posts'?'文章目录':'页面目录')+'</h3><div id="tree">'+treeHtml()+'</div></aside><section class="list panel" id="list"></section><section class="editor panel" id="editor"><div class="empty">从左侧选择文件。</div></section></div>';$('#q').value=state.query;$('#filter').value=state.filter;$('#q').oninput=e=>{state.query=e.target.value;renderList()};$('#filter').onchange=e=>{state.filter=e.target.value;renderList()};$('#newBtn').onclick=()=>newFile('_posts');$('#refresh').onclick=()=>{cache.clear();load()};$('#viewBtn').onclick=()=>{state.tree=!state.tree;render()};document.querySelectorAll('.tree-file').forEach(x=>{x.onclick=()=>openItem(x.dataset.id);x.ondragstart=e=>{e.dataTransfer.setData('text/plain',x.dataset.id)}});document.querySelectorAll('.tree-folder').forEach(x=>{x.onclick=()=>x.nextElementSibling?.classList.toggle('hidden');x.ondragover=e=>e.preventDefault();x.ondrop=e=>moveItem(e.dataTransfer.getData('text/plain'),x.dataset.path)});renderList()}
function renderList(){const q=state.query.toLowerCase(),arr=state.items.filter(i=>state.filter==='all'||(state.filter==='draft')===!!i.isDraft).filter(i=>!q||[i.title,i.source,join(i.tags),join(i.categories)].join(' ').toLowerCase().includes(q));$('#list').innerHTML=arr.map(i=>'<div class="item '+(state.selected?._id===i._id?'active':'')+'" data-id="'+i._id+'"><div class="title">'+esc(i.title||'未命名')+'</div><div class="meta">'+(i.isDraft?'草稿':'已发布')+' · '+esc(dateValue(i.date).replace('T',' '))+'<br>'+esc(i.source||'')+'</div></div>').join('')||'<div class="empty">没有匹配内容</div>';document.querySelectorAll('.item').forEach(x=>x.onclick=()=>openItem(x.dataset.id))}
async function openItem(id){if(state.dirty&&!confirm('当前修改未保存，放弃吗？'))return;const i=await api.get(state.mode+'/'+id);state.selected=i;state.dirty=false;renderList();editor(i)}
function editor(i){const post=state.mode==='posts';$('#editor').innerHTML='<div class="editor-head"><input id="title" value="'+esc(i.title||'')+'" placeholder="标题"><input id="date" type="datetime-local" value="'+esc(dateValue(i.date))+'"></div><div class="editor-meta"><input id="tags" value="'+esc(join(i.tags))+'" placeholder="标签，逗号分隔" '+(post?'':'disabled')+'><input id="cats" value="'+esc(join(i.categories))+'" placeholder="分类路径，例如 AI, MachineLearning, 随笔" '+(post?'':'disabled')+'><input id="author" value="'+esc(i.author||'PurslaneMa')+'" placeholder="作者"></div><div class="tabs"><button id="editTab" class="active">编辑</button><button id="previewTab">预览</button><span id="count" class="status"></span></div><textarea id="content" spellcheck="false">'+esc(i._content||'')+'</textarea><div id="preview" class="preview" hidden></div><div class="actions"><button id="saveBtn" class="primary">保存</button><span class="status">'+esc(i.source||'')+'</span></div>';const c=$('#content'),p=$('#preview'),set=v=>{$('#editTab').classList.toggle('active',v==='edit');$('#previewTab').classList.toggle('active',v==='preview');c.hidden=v!=='edit';p.hidden=v!=='preview';if(v==='preview')p.innerHTML=window.marked?marked.parse(c.value,{breaks:true,gfm:true}):'<pre>'+esc(c.value)+'</pre>'};['title','date','tags','cats','author','content'].forEach(k=>$('#'+k)?.addEventListener('input',()=>{state.dirty=true;$('#count').textContent=c.value.replace(/\s/g,'').length+' 字'}));$('#editTab').onclick=()=>set('edit');$('#previewTab').onclick=()=>set('preview');$('#saveBtn').onclick=save;$('#count').textContent=c.value.replace(/\s/g,'').length+' 字'}
async function save(){const p={title:$('#title').value,date:new Date($('#date').value||Date.now()).toISOString(),author:$('#author').value||'PurslaneMa',_content:$('#content').value};if(state.mode==='posts'){p.tags=split($('#tags').value);p.categories=split($('#cats').value)}await api.post(state.mode+'/'+state.selected._id,p);state.dirty=false;toast('已保存');await load()}
async function newFile(folder){const title=prompt('请输入文章标题');if(!title)return;await api.post('files/new',{title,folder:'source/'+folder});toast('文件已创建');await load()}
async function moveItem(id,folder){const i=state.items.find(x=>x._id===id);if(!i)return;const name=(i.source||'').split(/[\\/]/).pop();const r=await api.post('files/move',{from:'source/'+i.source,to:'source/'+folder+'/'+name});if(r.ok!==false){toast('文件已移动');await load()}}
function renderHelp(){$('#app').innerHTML='<section class="panel" style="padding:24px;line-height:1.9"><h2>使用说明</h2><p>文章和页面是两个独立工作区。左侧支持折叠、拖动文件、右键菜单和快速定位。</p><p>编辑器支持 Markdown、HTML、代码块、表格和 LaTeX 源码。</p></section>'}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));state.mode=b.dataset.mode;state.selected=null;state.tree=true;load()});$('#frontBtn').onclick=()=>open('/','_blank');$('#syncBtn').onclick=async()=>{await fetch('/admin/api/sync',{method:'POST'});toast('已开始同步到 GitHub')};document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();$('#q')?.focus()}if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='p'){e.preventDefault();$('#previewTab')?.click()}});load();
